project_id = "mcjgcgnsdiucbpzzsgsr"

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.learning-chat]
verify_jwt = false

[functions.get-learning-memory]
verify_jwt = false

[functions.update-learning-memory]
verify_jwt = false
